spring:
  application:
    name: hospital-search
  data:
    redis:
      host: jerry.world
      port: 6379
config:
  elasticsearch:
    scheme: http
    hostname: jerry.world
    port: 32200
management:
  endpoints:
    web:
      base-path: /actuator
  endpoint:
    health:
      show-details: always